name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Decode google-services.json from secret
        run: echo "${{ secrets.FIREBASE_CONFIG }}" > app/google-services.json

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
